const todasTurmas = [
    {codigo: "FGA0003", email: "bruno.ribas@unb.br , filomeno@unb.br"},
    {codigo: "FGA0006", email: "yehoshua@unb.br"},
    {codigo: "FGA0008", email: "rtoledo@unb.br"},
    {codigo: "FGA0013", email: "suelia@unb.br"},
    {codigo: "FGA0015", email: "chaffim@unb.br"},
    {codigo: "FGA0017", email: "waamaral@unb.br"},
    {codigo: "FGA0023", email: "ritasilva@unb.br"},
    {codigo: "FGA0025", email: "jcormane@unb.br"},
    {codigo: "FGA0030", email: "john.gardenghi@unb.br"},
    {codigo: "FGA0034", email: "viniciusrispol@unb.br"},
    {codigo: "FGA0037", email: "reis.william@unb.br"},
    {codigo: "FGA0038", email: "olexiy@unb.br"},
    {codigo: "FGA0039", email: "andrianov@unb.br"},
    {codigo: "FGA0040", email: "rafael.rodrigues@unb.br"},
    {codigo: "FGA0043", email: "olexiy@unb.br"},
    {codigo: "FGA0044", email: "thiagocordeiro@unb.br"},
    {codigo: "FGA0045", email: "polliana.martins@unb.br"},
    {codigo: "FGA0047", email: "andreiaacosta@unb.br"},
    {codigo: "FGA0048", email: "reis.william@unb.br"},
    {codigo: "FGA0050", email: "shscarneiro@unb.br"},
    {codigo: "FGA0052", email: "jungpyo@unb.br"},
    {codigo: "FGA0053", email: "edsonalves@unb.br"},
    {codigo: "FGA0054", email: "wandercleber@unb.br"},
    {codigo: "FGA0055", email: "rhander@unb.br"},
    {codigo: "FGA0056", email: "cueva@unb.br"},
    {codigo: "FGA0060", email: "vandorissoli@gmail.com"},
    {codigo: "FGA0063", email: "rafael.mendes@unb.br"},
    {codigo: "FGA0066", email: "viniciusrispol@unb.br"},
    {codigo: "FGA0067", email: "filomeno@unb.br, evgarcia@unb.br , loana@unb.br"},
    {codigo: "FGA0068", email: "gbeserra@unb.br"},
    {codigo: "FGA0069", email: "robertobaptista@unb.br"},
    {codigo: "FGA0070", email: "tiago.brito@unb.br"},
    {codigo: "FGA0071", email: "henriquemenegaz@unb.br, claudiaochoa@unb.br, andrade@unb.br"},
    {codigo: "FGA0072", email: "gbeserra@unb.br"},
    {codigo: "FGA0073", email: "rvlopes@unb.br"},
    {codigo: "FGA0074", email: "damuz@unb.br"},
    {codigo: "FGA0075", email: "emmanuel@unb.br, sandraluz@unb.br,ramunoz@unb.br" },
    {codigo: "FGA0076", email: "abso@unb.br, fabioalfaia@unb.br"},
    {codigo: "FGA0078", email: "emmanuel@unb.br,ramunoz@unb.br"},
    {codigo: "FGA0083", email: ""},
    {codigo: "FGA0084", email: ""},
    {codigo: "FGA0085", email: "crisloesch@gmail.com"},
    {codigo: "FGA0086", email: "jcormane@unb.br, fhsilva@unb.br"},
    {codigo: "FGA0087", email: "jcormane@unb.br, rudi@unb.br"},
    {codigo: "FGA0088", email: "fhsilva@unb.br"},
    {codigo: "FGA0089", email: "rudi@unb.br"},
    {codigo: "FGA0090", email: "eberth@unb.br"},
    {codigo: "FGA0091", email: "jvazgoulart@gmail.com"},
    {codigo: "FGA0092", email: "daniel.c.araujo@gmail.com"},
    {codigo: "FGA0093", email: "filomeno@unb.br,thiagocordeiro@unb.br" },
    {codigo: "FGA0096", email: "guillermo@unb.br"},
    {codigo: "FGA0098", email: ""},
    {codigo: "FGA0099", email: "waamaral@unb.br"},
    {codigo: "FGA0100", email: "gerardo_idrobo@unb.br"},
    {codigo: "FGA0101", email: "batistuta@unb.br"},
    {codigo: "FGA0102", email: "chaffim@unb.br ,lucianofonseca@unb.br"},
    {codigo: "FGA0103", email: ""},
    {codigo: "FGA0104", email: "roseany@unb.br, andreiaacosta@unb.br"},
    {codigo: "FGA0105", email: "rtoledo@unb.br"},
    {codigo: "FGA0106", email: "polliana.martins@unb.br"},
    {codigo: "FGA0107", email: "eberth@unb.br"},
    {codigo: "FGA0108", email: "edsonalves@unb.br"},
    {codigo: "FGA0109", email: "renatocoral@unb.br"},
    {codigo: "FGA0119", email: "andrepenna@unb.br"},
    {codigo: "FGA0120", email: "gerardo_idrobo@unb.br"},
    {codigo: "FGA0121", email: "shscarneiro@unb.br"},
    {codigo: "FGA0124", email: "serrano@unb.br"},
    {codigo: "FGA0130", email: "fscardua@unb.br"},
    {codigo: "FGA0131", email: "evandroleonardo@unb.br"},
    {codigo: "FGA0132", email: "claudiaochoa@unb.br"},
    {codigo: "FGA0133", email: "glauceny.medeiros@unb.br, rudi@unb.br,ambrasil@unb.br" },
    {codigo: "FGA0134", email: "wandercleber@unb.br, bruno.ribas@unb.br"},
    {codigo: "FGA0137", email: "serrano@unb.br, glauco.pedrosa@unb.br"},
    {codigo: "FGA0138", email: "ricardoajax@unb.br, caguiar@unb.br, hilmer@unb.br"},
    {codigo: "FGA0141", email: "vitferrari@gmail.com"},
    {codigo: "FGA0142", email: "fonsecafga@unb.br"},
    {codigo: "FGA0147", email: "niltoncs@unb.br, rose.shimizu@unb.br"},
    {codigo: "FGA0148", email: "zizanunes@gmail.com"},
    {codigo: "FGA0150", email: "rafael.rodrigues@unb.br,jungpyo@unb.br , jpetrocchi@unb.br, ricardoajax@unb.br"},
    {codigo: "FGA0152", email: "mateusmiranda@unb.br"},
    {codigo: "FGA0154", email: "glauceny.medeiros@unb.br, avilas@unb.br"},
    {codigo: "FGA0155", email: "eneidagv@unb.br"},
    {codigo: "FGA0156", email: "roseany@unb.br, fcarbajal@unb.br"},
    {codigo: "FGA0157", email: "mariliamfg@unb.br, rmiracer@unb.br"},
    {codigo: "FGA0158", email: "andrelanna@unb.br, hgmoura@yahoo.com,glauco.pedrosa@unb.br"},
    {codigo: "FGA0160", email: "lucianofonseca@unb.br, lbcarval@unb.br, rmiracer@unb.br"},
    {codigo: "FGA0161", email: "josiane@unb.br, fscardua@unb.br, vitferrari@gmail.com"},
    {codigo: "FGA0163", email: "fragelli@unb.br ,patriciabraga@unb.br, rudi@unb.br"},
    {codigo: "FGA0164", email: "sandralima@unb.br, vcastro@unb.br"},
    {codigo: "FGA0166", email: "fabianosoares@unb.br"},
    {codigo: "FGA0167", email: "sbkhalil@unb.br"},
    {codigo: "FGA0168", email: "himilsys@unb.br, sbkhalil@unb.br, mateusmiranda@unb.br,eneidagv@unb.br" },
    {codigo: "FGA0169", email: "ambrasil@unb.br"},
    {codigo: "FGA0170", email: "daniel.sundfeld@unb.br"},
    {codigo: "FGA0172", email: "cristianesramos@unb.br ,georgemarsicano@unb.br "},
    {codigo: "FGA0173", email: "rejanecosta@unb.br"},
    {codigo: "FGA0174", email: "josiane@unb.br"},
    {codigo: "FGA0175", email: "storti@unb.br"},
    {codigo: "FGA0177", email: "pilar@unb.br"},
    {codigo: "FGA0179", email: "ritasilva@unb.br"},
    {codigo: "FGA0184", email: "rejanecosta@unb.br,marioand@unb.br "},
    {codigo: "FGA0188", email: "ramunoz@unb.br"},
    {codigo: "FGA0190", email: "abso@unb.br"},
    {codigo: "FGA0191", email: "sandraluz@unb.br,emmanuel@unb.br "},
    {codigo: "FGA0194", email: "fabiolisboa@unb.br"},
    {codigo: "FGA0195", email: "marioand@unb.br"},
    {codigo: "FGA0198", email: "damuz@unb.br"},
    {codigo: "FGA0204", email: "ambrasil@unb.br"},
    {codigo: "FGA0206", email: "hilmer@unb.br, ricardoc@unb.br"},
    {codigo: "FGA0208", email: "mileneserrano@unb.br"},
    {codigo: "FGA0210", email: "mileneserrano@unb.br"},
    {codigo: "FGA0211", email: "fwcruz@gmail.com, fonsecafga@unb.br, clenio.fonseca@unb.br"},
    {codigo: "FGA0214", email: "bruno.pereira@unb.br"},
    {codigo: "FGA0219", email: "cristiano.jacques@gmail.com"},
    {codigo: "FGA0221", email: "fabianosoares@unb.br"},
    {codigo: "FGA0226", email: "evandroleonardo@unb.br"},
    {codigo: "FGA0228", email: "anflor@unb.br"},
    {codigo: "FGA0229", email: ""},
    {codigo: "FGA0230", email: "avilas@unb.br"},
    {codigo: "FGA0232", email: "hgmoura@yahoo.com"},
    {codigo: "FGA0236", email: "pilar@unb.br"},
    {codigo: "FGA0238", email: "elainevenson@unb.br"},
    {codigo: "FGA0240", email: "renatocoral@unb.br"},
    {codigo: "FGA0242", email: "andrelanna@unb.br"},
    {codigo: "FGA0244", email: "fwcruz@gmail.com"},
    {codigo: "FGA0250", email: "alexreis@unb.br, suelia@unb.br, caguiar@unb.br,rafael.mendes@unb.br, rhander@unb.br "},
    {codigo: "FGA0251", email: "fabiolisboa@unb.br, manuelbarcelos@unb.br"},
    {codigo: "FGA0252", email: "rudi@unb.br"},
    {codigo: "FGA0254", email: "possa@unb.br"},
    {codigo: "FGA0258", email: "evgarcia@unb.br"},
    {codigo: "FGA0261", email: "guillermo@unb.br, robertobaptista@unb.br, sebastien@unb.br,batistuta@unb.br "},
    {codigo: "FGA0262", email: "loana@unb.br"},
    {codigo: "FGA0265", email: "rudi@unb.br, ambrasil@unb.br"},
    {codigo: "FGA0266", email: "zizanunes@gmail.com"},
    {codigo: "FGA0267", email: "hgmoura@yahoo.com"},
    {codigo: "FGA0270", email: "bruno.pereira@unb.br"},
    {codigo: "FGA0274", email: "wandercleber@unb.br"},
    {codigo: "FGA0278", email: "cristianesramos@unb.br"},
    {codigo: "FGA0280", email: "sandrohaddad@unb.br"},
    {codigo: "FGA0284", email: "fabiolisboa@unb.br"},
    {codigo: "FGA0285", email: "anflor@unb.br"},
    {codigo: "FGA0286", email: "manuelbarcelos@unb.br"},
    {codigo: "FGA0291", email: "andrianov@unb.br"},
    {codigo: "FGA0292", email: "sebastien@unb.br"},
    {codigo: "FGA0301", email: "alexreis@unb.br"},
    {codigo: "FGA0380", email: "cristiano.jacques@gmail.com"},
    {codigo: "MAT0025", email: "taneguti@unb.br, fragelli@unb.br,matheusbernardini@unb.br, tatilista@unb.br"},
    {codigo: "MAT0026", email: "taneguti@unb.br, tatilista@unb.br, taisca@unb.br"},
    {codigo: "MAT0027", email: "matheusbernardini@unb.br"},
    {codigo: "MAT0031", email: "INTRODUCAO A ALGEBRA LINEAR"},
    {codigo: "IFD0171", email: "ronniamorim@unb.br, wytler.cordeiro@unb.br,morgado@unb.br"},
    {codigo: "IFD0173", email: "tiago.brito@unb.br, wytler.cordeiro@unb.br, morgado@unb.br,ronniamorim@unb.br, leandrocardoso@unb.br"},
  ]
  
  export default todasTurmas
  